export const RAWDATA = {
  imageUrl: "",
  volume: 26.47,
  rawPrice: 168,
  material: {
    name: "8200树脂",
    key: "material",
    val: "",
    img: "",
    advantages: "高精度,高韧性, 高稳定性",
    disAdvantages: "保存温度不宜超过60摄氏度",
    color: {
      hex: "#F4DA40",
      pantone: "7404 C",
    },
    deviation: "±200微米或±0.2%",
    price: 14.6,
  },
  grinding: {
    name: "精磨",
    key: "grinding",
    val: "",
    status: true,
    price: "23",
  },
  braces: {
    name: "牙套",
    key: "grinding",
    status: false,
    total: [],
    price: "23",
  },
  nuts: {
    name: "铜螺母",
    key: "nuts",
    status: false,
    price: "23",
    total: [],
  },
  paint: {
    name: "喷漆",
    key: "paint",
    status: false,
    price: "23",
  },
  count: { name: "数量", key: "count", val: 1 },
  deliveryTime: { name: "交期", key: "deliveryTime", price: 0, val: "24小时" },
  finalPrice: 168,
}
