export const RAWDATA = {
  imageUrl: "",
  volume: 26.47,
  material: {
    id: 315,
    name: "光敏树脂",
    default_code: "C-UV 9400",
    list_price: 500,
    categ_big_name: "原材料",
    categ_material_name: "树脂",
    starting_price: 0,
    material_density: 1.4,
    material_density_uom: "cm²",
    price: 0,
  },
  grinding: {
    name: "精磨",
    key: "grinding",
    val: "",
    status: false,
    price: 0,
  },
  braces: {
    name: "牙套",
    key: "grinding",
    status: false,
    total: [],
    price: 0,
  },
  nuts: {
    name: "铜螺母",
    key: "nuts",
    status: false,
    price: 0,
    total: [],
  },
  paint: {
    name: "喷漆",
    key: "paint",
    colorList: {
      c: [],
      u: [],
    },
    status: false,
    price: 0,
  },
  count: { name: "数量", key: "count", val: 1 },
  deliveryTime: { name: "交期", key: "deliveryTime", price: 0, val: "24小时", currentIndex: 2 },
  finalPrice: 168,
}
