export const RAWDATA = {
  imageUrl: "",
  volume: 26.47,
  rawPrice: 168,
  material: "8200树脂",
  grinding: {
    status: false,
    price: 0,
  },
  braces: {
    name: "牙套",
    status: false,
    total: [],
    price: 0,
  },
  nuts: {
    name: "铜螺母",
    status: false,
    price: 0,
    total: [
      { type: "M1.6*3", length: "4.5", diameter: "2.2", outerDiameter: "5.2", num: 0 },
      { type: "M2*2", length: "3.5", diameter: "3.2", outerDiameter: "6.2", num: 0 },
      { type: "M2*3", length: "4.5", diameter: "3.2", outerDiameter: "6.2", num: 0 },
      { type: "M2*5", length: "6.5", diameter: "3.2", outerDiameter: "6.2", num: 0 },
      { type: "M2.5*3", length: "4.5", diameter: "3.9", outerDiameter: "6.2", num: 0 },
      { type: "M3*3", length: "4.5", diameter: "3.8", outerDiameter: "6.8", num: 0 },
      { type: "M3*5", length: "6.5", diameter: "3.8", outerDiameter: "6.8", num: 0 },
      { type: "M4*4", length: "5.5", diameter: "4.8", outerDiameter: "7.8", num: 0 },
      { type: "M4*8", length: "9.5", diameter: "4.8", outerDiameter: "7.8", num: 0 },
      { type: "M5*5", length: "6.5", diameter: "5.9", outerDiameter: "9.1", num: 0 },
      { type: "M6*5", length: "7.5", diameter: "7.9", outerDiameter: "11.9", num: 0 },
      { type: "M8*10", length: "11.5", diameter: "9.8", outerDiameter: "13.8", num: 0 },
    ],
  },
  paint: {
    name: "喷漆",
    colorList: {
      c: [],
      u: [],
    },
    status: false,
    price: 0,
  },
  count: { name: "数量", val: 1 },
  deliveryTime: { name: "交期", price: 0, val: "24小时" },
  finalPrice: 168,
}
