/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alpha: typeof import('./src/components/colorPicker/color/Alpha.vue')['default']
    AxisLine: typeof import('./src/components/modelViewer/AxisLine.vue')['default']
    Box: typeof import('./src/components/colorPicker/color/Box.vue')['default']
    BracesPanel: typeof import('./src/components/dialogs/BracesPanel.vue')['default']
    ColorList: typeof import('./src/components/colorPicker/ColorList.vue')['default']
    ColorPicker: typeof import('./src/components/colorPicker/color/ColorPicker.vue')['default']
    Colors: typeof import('./src/components/colorPicker/color/Colors.vue')['default']
    copy: typeof import('./src/components/modelViewer/ThreeViewer copy.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Hue: typeof import('./src/components/colorPicker/color/Hue.vue')['default']
    MaterialPanel: typeof import('./src/components/dialogs/MaterialPanel.vue')['default']
    NutsPanel: typeof import('./src/components/dialogs/NutsPanel.vue')['default']
    PantoneList: typeof import('./src/components/colorPicker/PantoneList.vue')['default']
    Preview: typeof import('./src/components/colorPicker/color/Preview.vue')['default']
    Saturation: typeof import('./src/components/colorPicker/color/Saturation.vue')['default']
    SelectedPanel: typeof import('./src/components/colorPicker/SelectedPanel.vue')['default']
    Sucker: typeof import('./src/components/colorPicker/color/Sucker.vue')['default']
    ThreeViewer: typeof import('./src/components/modelViewer/ThreeViewer.vue')['default']
    'ThreeViewer copy': typeof import('./src/components/modelViewer/ThreeViewer copy.vue')['default']
    XzzColorPicker: typeof import('./src/components/colorPicker/XzzColorPicker.vue')['default']
  }
}
