export const aa = {
  material: {
    id: 315,
    name: "光敏树脂",
    default_code: "C-UV 9400",
    list_price: 500,
    categ_big_name: "原材料",
    categ_material_name: "树脂",
    starting_price: 0,
    material_density: 1.4,
    material_density_uom: "cm²",
    price: 0,
  },
  grinding: {
    name: "精磨",
    key: "grinding",
    val: "",
    status: true,
    price: 89.58,
    rawPrice: 89.58,
    checkDisabled: true,
  },
  braces: {
    name: "牙套",
    key: "grinding",
    status: true,
    total: [
      {
        id: 324,
        image: "/web/image?model=product.template&id=324&field=image_128&unique=1722049832089",
        name: "牙套",
        default_code: "M3(1D-3D)",
        list_price: 2.5,
        categ_big_name: "零配件库",
        categ_material_name: "牙套",
        starting_price: 0,
        material_density: 0,
        material_density_uom: false,
        material_group_id: 4,
        device_id: false,
        color: false,
        material_advantages: false,
        material_disadvantages: false,
        error_and_precision: false,
        material_shrinkage: false,
        fastest_delivery: false,
        equipment_size: false,
        experts_recommend: false,
        variants: [
          {
            id: 334,
            name: "[M3(1D-3D)] 牙套",
            default_code: "M3(1D-3D)",
            list_price: 2.5,
            attribute_values: {
              孔底深度: "3*1d-3d加1.5",
              底孔直径: "3.1",
              工件外径: "6.1",
            },
          },
        ],
        num: 1,
      },
    ],
    price: 2.5,
  },
  nuts: {
    name: "铜螺母",
    key: "nuts",
    status: true,
    price: 1,
    total: [
      {
        id: 130,
        image: "/web/image?model=product.template&id=130&field=image_128&unique=1722049832091",
        name: "铜螺母",
        default_code: "M1.6*3",
        list_price: 1,
        categ_big_name: "零配件库",
        categ_material_name: "螺母",
        starting_price: 0,
        material_density: 0,
        material_density_uom: false,
        material_group_id: 5,
        device_id: false,
        color: false,
        material_advantages: false,
        material_disadvantages: false,
        error_and_precision: false,
        material_shrinkage: false,
        fastest_delivery: false,
        equipment_size: false,
        experts_recommend: false,
        variants: [
          {
            id: 140,
            name: "[M1.6*3] 铜螺母",
            default_code: "M1.6*3",
            list_price: 1,
            attribute_values: {
              长度: "4.5",
              底孔直径: "2.2",
              工件外径: "5.2",
            },
          },
        ],
        num: 1,
      },
    ],
  },
  paint: {
    colorList: {
      c: [
        {
          hex: "#FF8200",
          rgb: [255, 130, 0],
          pantone: "151 C",
        },
      ],
      u: [
        {
          hex: "#00B4E4",
          rgb: [0, 180, 228],
          pantone: "306 U",
        },
      ],
    },
    price: 0,
  },
  count: {
    name: "数量",
    key: "count",
    val: 1,
  },
  deliveryTime: {
    name: "交期",
    key: "deliveryTime",
    price: 0,
    val: "24小时",
    currentIndex: 2,
  },
  finalPrice: 288.33,
  model3d: {
    width: 22.8,
    height: 45,
    depth: 50,
    volume: 22973.62,
    surfaceArea: 8958.07,
  },
  modelFileInfo: {
    filePath: "blob:http://localhost:666/fe2e2827-8f16-424b-bb91-6537813f55d7",
    fileType: "stl",
    fileName: "底座__00.stl",
    size: "22.80x45.00x50.00",
    volume: 22973.62,
    surfaceArea: 8958.07,
  },
}
